### ISSUE TITLE
Feature Request:  Expand `with` method to include joins

### ISSUE THREAD

**Issue by jclausen** [coldbox-modules/quick#134]
The `with` method on the `BaseEntity` provides eager loading of the relationships on the query via sub-select, however it does not allow for aliasing or ordering by those relationships, without going down in to the builder and then back up to the entity.

On `to-one` relationships the eager fetching of relations is unnecessary and could be accomplished with a JOIN using the `with` method.

Suggestion:  Allow a second argument on `with` that designates a join, and allow for textual input as well as boolean:

example:

```
getInstance( "Book" ).with( "author", true );  //  INNER/FULL JOIN
getInstance( "Book" ).with( "author", "inner" );  //  INNER/FULL JOIN
getInstance( "Book" ).with( "author", "left" ); // left
getInstance( "Book" ).with( "author", "right outer" ); // right outer join
```

Once the join is enabled, the alias of the join should match the name provided and the nested entities can be hydrated directly from the query results.

This allows for additional querying without the need to pass in raw SQL or qb subquery instances:

```
getInstance( "Book" )
    .with( "author", true )
    .with( "author.publisher", true )
    .where( "author.publisher.name", "Penguin" )
    .orderBy( "author.lastName", "ASC" )
    .get()
```

Additional Suggestion: Allow function annotation on relationships to designate an eager fetching strategy:

```
function Author() eagerFetch="join"{
        return belongsTo( "Author", "FK_author" );
}
```

or via comment annotation, since Quick captures this info:

```
/**
* @eagerFetch join
**/
function Author(){
        return belongsTo( "Author", "FK_author" );
}
```

**Comment by elpete** [comment]
Quick let's you write queries that get you the same end result without raw SQL calls.  Here's what it might look like:
```cfc
var books = getInstance( "Book" )
    .with( "author.publisher" ) // The first `with` call is redundant since we are loading nested relationships here
    .whereHas( "author.publisher", ( qb ) => {
        qb.where( "name", "Penguin" );
    } )
    .orderBy( "author.lastName", "ASC" ) // this already works in Quick
    .get();
```
It is true that this will use subselects instead of joins, but I have yet to see a significant performance difference between subselects and joins.  If you have some benchmarks that show otherwise, please re-open this issue with them and I will review again.

In the meantime, I did add a new issue to make that `whereHas` to check the publisher name a bit more ergonomic: https://github.com/coldbox-modules/quick/issues/143
