### ISSUE TITLE
v5 regression in when trying to apply a where clause without chaining methods

### ISSUE THREAD

**Issue by ryanalbrecht** [coldbox-modules/quick#198]
On quick v5 there seems to an issue when trying to apply a where clause without using method chaining. 

```	
	// this does work
	var entity = getInstance('Device').where('id',4);

	// this does NOT work
	var entity = getInstance('Device')
	local.entity.where('id',4);

	var result = entity.get();
	writeDump(var=result, top=2);
```

**Comment by davidAtInleague** [comment]
Looks like it returns a new copy instead of mutating itself. e.g. the following now seems required
```
entity = local.entity.where('id', 4);
```

It's tough because it alters the meaning of existing code, without triggering loud failures. Old v4 code continues to run, and perform queries against the db, and return result sets, but it might not select what it used to (that last entity.get() is really "just" `getInstance("Device").get()`, unconstrained).

After I typed the "unconstrained" word above, I saw a possible connection to https://github.com/coldbox-modules/quick/issues/195
