### ISSUE TITLE
Support compound keys in relationships

### ISSUE THREAD

**Issue by elpete** [coldbox-modules/quick#56]
(This may already exist and I just don't know about it, but I don't think it's in the docs...)

If a relationship has a compound key, right now you can get it if you do something like this, where a Rating maps to a registration by childID and seasonID:
```
function registration() { return belongsTo( relationName = "Registration", foreignKey = "childID" )
    .whereSeasonID( this.getSeasonID() ); }
```

This is really cool. 

The only drawback is that it requires that the whole object is loaded before the relationship can be got, which means you can't eager load a relationship this way. I can't remember how exactly it fails - whether it just uses the seasonID from the first entity or just doesn't construct the query correctly – but it makes sense that it fails since eager loading works off the relationship attributes and the relationship doesn't know that there is more than one key.

**Comment by elpete** [comment]
@MordantWastrel I am not positive, but I think this is working in the current `development` version.  Would love for you to test if you could.

**Comment by MordantWastrel** [comment]
@elpete What is the syntax for a compound key? 

We are swamped for the next couple of weeks but if I get a chance to test it, I will.

**Comment by elpete** [comment]
I believe your syntax above should work.

**Comment by MordantWastrel** [comment]
Hmm, that syntax is the current workaround and requires a loaded object. It's not really ideal for a model definition, though. Even if it worked (in the sense that it would use the `seasonID` column rather than requiring that the object be loaded and have a `seasonID` attribute populated) -- it's not readable to a developer as a compound key.

I'd like to be able to do:

`function registration() { return belongsTo( relationName = "Registration", foreignKey = [ "childID", "seasonID" ] )`

**Comment by elpete** [comment]
You are absolutely right.  This is not a simple change, unfortunately.  Sorry for the false early hope.
