### ISSUE TITLE
Scopes using .whereIn closures are resolving using the entity parent

### ISSUE THREAD

**Issue by MordantWastrel** [coldbox-modules/quick#76]
On a **registrations** entity, we have the following scope:

```
function scopeForFamily( query, string familyID ) {
        return query.whereIn( "childID", function ( sQ ) {
            sQ.select( "childID" )
                .from( "children" )
                .whereFamilyID( familyID );
        } );
    }
```

In Quick 3 this produces:

```
WHERE [registrations].[childID] IN (SELECT [registrations].[childID] FROM [children] WHERE [registrations].[FamilyID] = 'C3D244D1-D983-41ED-A76C-0AB0C47C4F83')
```

It is resolving the `whereFamilyID()` statement with the scope entity's table (registrations) rather than the .from() inside the closure. This did not occur in Quick v2.

Same behavior if you write out the .where() without the onMissingMethod.

**Comment by elpete** [comment]
Were you able to check if the same behavior existed when using `newEntity( “Child” )` to create the query instead of a closure?

This is tricky because while you set the table name, the entity is still the `Registration` entity. We could use the set table name, but there would be other gotchas like calling scopes. 

I’m curious what others think? Is there ever a valid reason to call `from` or `table` on a Quick entity? The only use case I can think is aliasing a table. If we solve that with another method, maybe we can give a useful error message when calling `from`. 

Thoughts?

**Comment by MordantWastrel** [comment]
No, newEntity didn't work.  It either got:

`the function normalizeToArray has an invalid return value , can't cast Object type [Component model.q.Child.qChild] to a value of type [array]`

...or if I forced it into an array:

`Component [model.q.Child.qChild] has no accessible Member with name [VALUE] QueryUtils.cfc:32`

It's really just a backwards compatibility question for us. Because Quick v2 didn't have the `.has()` stuff, we have code like this all over all of our apps.  The use case is a scope that checks for the entity's existence in some other table. That other table may or may not have a Quick entity attached to it, so .has() only works with defined relationships. It seems pretty tough to say that you can't use .from() in a Quick scope!

**Comment by MordantWastrel** [comment]
Out of curiosity, what is it that changed between v2 and v3 such that this worked before and has the table name/entity gotchas?

**Comment by elpete** [comment]
Some of the `*Through` relationships became recursive and we needed to
qualify the table.  It also affected `belongsToMany` where we join and the
column was ambiguous.

**Comment by elpete** [comment]
I have a fix for this, but it comes with a caveat.  Take this example:
```cfc
var users = getInstance( "User" )
	.whereIn( "id", function( q ) {
		q.from( "my_posts" )
			.select( "user_id" )
			.whereNotNull( "published_date" );
	} )
	.get();
```
This will work as expected.  `user_id` and `published_date` will be qualified with `my_posts`.
```cfc
var users = getInstance( "User" )
	.whereIn( "id", function( q ) {
		q.select( "user_id" )
			.from( "my_posts" )
			.whereNotNull( "published_date" );
	} )
	.get();
```
This will fail saying that `users.user_id` is not a valid column.  This is because columns go through the column formatter immediately, not at build time.  Now that might be a good qb enhancement, but it isn't how it currently works.

Additionally, no aliases or scopes will be available on these entities.  Using `has` and `whereHas` are preferred or even passing a separate builder instance to the `whereIn` call: `newEntity( "Post" ).select( "user_id" ).whereNotNull( "publishedDate" ).retrieveQuery();`.

That being said, I am going to merge the fix because it doesn't make sense to ignore a configured table.  Additionally, I'll open a qb ticket to do the column formatting lazily.  That would be a big undertaking, but it probably is more forgiving.

**Comment by MordantWastrel** [comment]
This makes sense (and helps me understand what the original problem was). I think it's a perfectly good compromise given what a quick fix it is, and with the `whereHas` fix we'll be tempted to just "do it right" anyway!

**Comment by MordantWastrel** [comment]
I presume it's not easily possible to detect the second case, because it's easy enough when it throws an error for column not found but problematic when the column exists in both tables and it appears to be working -- but is selecting the value from the wrong table.
